Repository rebase-helper/rebase-helper, pull requests merged in 2018-04, with the labels that each got.

#484 Fix more issues with paths
  rebasehelper/application.py
  rebasehelper/specfile.py
Labels: bug

#485 Update .gitignore file when using --update-sources
  rebasehelper/application.py
  rebasehelper/tests/test_application.py
  rebasehelper/utils.py
Labels: enhancement

#439 Add license checker
  rebasehelper/application.py
  rebasehelper/checkers/licensecheck_tool.py
  setup.py
Labels: checkers
