Repository rebase-helper/rebase-helper, pull requests merged in 2019-07, with the labels that each got.

#633 Log reason of patching failures
  rebasehelper/patcher.py
Labels: patches

#634 Check also functions without type annotations using mypy
  tox.ini
Labels: unit tests

#649 Documentation update
  docs/api/buildhelper.rst
  docs/api/index.rst
  docs/api/outputtool.rst
  docs/api/patcher.rst
  docs/api/patchhelper.rst
  docs/api/plugins.rst
  docs/api/plugins/buildloghooks.rst
  docs/api/plugins/buildtools.rst
  docs/api/plugins/checker.rst
  docs/api/plugins/outputtools.rst
  docs/api/plugins/plugincollection.rst
  docs/api/plugins/pluginmanager.rst
  docs/api/plugins/rpmbuildtools.rst
  docs/api/plugins/spechooks.rst
  docs/api/plugins/srpmbuildtools.rst
  docs/api/plugins/versioneer.rst
  docs/user_guide/installation.rst
  docs/user_guide/writing_plugins.rst
Labels: documentation

#652 Fix listing default checkers
  rebasehelper/plugins/checkers/__init__.py
Labels: bug

#653 Add RTD config file
  .readthedocs.yml
Labels: documentation

#655 Allow wrapping options in generated HTML documentation
  docs/_static/css/custom.css
  docs/conf.py
Labels: documentation

#656 Wrap lines exceeding max width in man page synopsis
  docs/ext/autoargs.py
  docs/ext/custom_man_builder.py
  docs/man/rebase-helper.rst
Labels: documentation
